### ISSUE TITLE
Add optional "automate" boolean to settlement demo

### ISSUE THREAD

**Issue by tim-mchale** [hashgraph/hedera-hcs-sxc-java#361]
**Problem**
Sometimes the settlement demo flow seems overly complex because of manual step-by-step message flow. The manual flow is good when necessary, but could be complemented by a faster version.

**Solution**
- Add a boolean "automate" parameter to each settlement business message
- add a checkbox to the create credit and create settlement UI to set that message
- modify demo logic to propagate "automate" to each successive message within a thread
- modify UI to hide buttons on automated threads
- modify demo logic to set sensible defaults (and pick a random payment channel) for other messages

**Comment by zoperado** [comment]
Indeed. It is worth checking if automating all ACKs  would make the  flow more natural. ACKs could happen at the transition diagram level.
