### ISSUE TITLE
Settlement demo - allow concurrent UI operations

### ISSUE THREAD

**Issue by tim-mchale** [hashgraph/hedera-hcs-sxc-java#362]
**Problem**
Disabled UI and "progress bar" is unnecessary and prevents participants from sending more messages while waiting for responses. It also makes things appear slow. Why shouldn't Alice be able to send more credits to Bob while waiting for him to agree to the first one. 

**Solution**
Remove progress bar. Leave UI enabled.

**Comment by zoperado** [comment]
Alice can send more credits to anyone else but Bob. The UI is disabled only for Bob and when it becomes enabled again it is a clue that something has changed. To demonstrate speed Alice can send new credits to every other participant; this should work in parallel. It requires deep changes in the app logic and to how things are redrawn when new info is available to change this pattern. We could allow the new credit button to be outside of the disabled area to allow creation of new credits for the same participant.

**Comment by gregscullard** [comment]
Updated UI to allow credits to be created more efficiently, however doing the same for settlement (and other buttons) allows the user to click on the same button several times.
Further work would be required to disable buttons on closure of the dialogs until a notification/refresh occurs.
