### ISSUE TITLE
Java: simple-message demo fails to send transactions when missing submission key property in config.yaml

### ISSUE THREAD

**Issue by zoperado** [hashgraph/hedera-hcs-sxc-java#367]
**Detailed Description**

**Actual Behavior**

**Expected Behavior**

**Environment:**
- Java: [e.g. OpenJDK 11.0.4]
- Node: [e.g. v12.9.1-x86]
- OS: [e.g. Ubuntu 18.04]
- Version: [e.g. 1.0.1]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by gregscullard** [comment]
Unable to reproduce this with latest code

**Comment by zoperado** [comment]
seems to have been fixed here too
