### ISSUE TITLE
OnHCSMessageCallback.java - identify encryption override

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-hcs-sxc-java#371]
**Detailed Description**
When receiving a message, it's possible that the message is encrypted even if the `encryptMessages` flag is false. A client could override encryption and encrypt a message amongst other non-encrypted messages.

**Actual Behavior**
Currently, we use the `encryptMessages` flag to determine if a message is encrypted, this is incorrect for the reason above.

**Expected Behavior**
An application message should include a boolean to indicate if the message is encrypted or not, this allows for per-message override.
If the boolean is `true`, attempt to decrypt, if it's `false` do not decrypt.

When sending a message, set the application message `encrypted` flag to true if `encryptMessages` is true, else set it to the `overrideEncryptMessages` value.

**Environment:**
- Java: [e.g. OpenJDK 11.0.4]
- Node: [e.g. v12.9.1-x86]
- OS: [e.g. Ubuntu 18.04]
- Version: [e.g. 1.0.1]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by zoperado** [comment]
Our current ApplicationMessage is
``
`message ApplicationMessage {
    ApplicationMessageID applicationMessageId = 1;

    bytes businessProcessMessage = 2;  // the payload
    bytes unencryptedBusinessProcessMessageHash  = 3;
    bytes businessProcessSignatureOnHash  = 4;
    bytes encryptionRandom = 5;  // random number used for ivspec. it doubles as a flag to test if message is encrypted, not set means that message is not encrypted
}
```
where we agree that `encryptionRandom` can double as a flag to indicate whether a message is encrypted (it is not set for unenrcrypted messages).

**Comment by zoperado** [comment]
Remains to test if encrypted even if the encryptMessages flag is false (because producer could have used override)

**Comment by zoperado** [comment]
Need to use convention that when encryption flag is set then we consult the addressbook. 
The on the receiving end, when a message is encrypted then we do not check address book but need to get the shared key either from env or an override.
