### ISSUE TITLE
Audit Thread UI - message summary fields

### ISSUE THREAD

**Issue by tim-mchale** [hashgraph/hedera-hcs-sxc-java#391]
**Problem**
Missing fields from audit thread summary view.

**Solution**
Add the following common fields (for both encrypted and unencrypted messages)
- consensus timestamp
- topic id
- topic sequence number

**Additional Context**
Having the topic id and sequence number more obvious also makes it easier to find messages (cross-reference) on mirror explorers.

**Comment by zoperado** [comment]
@tim-mchale  there is no single consensus number or sequence no  bc of chunking. We should add a consensus number in the ApplicationMessage which is either the consensus of the first chunk or last chunk. @gregscullard we would need to alter `protobuf` to accommodate this.
