### ISSUE TITLE
hcs-sxc-core: address book for symmetric encryption

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-hcs-sxc-java#408]
**Problem**
The address book in core doesn't hold the necessary data for symmetric encryption.
This needs to be implemented in both the H2 and in-memory database plugins

**Solution**
* Core needs keys to be able to manage decryption
* The address book in core should contain the following
  * UserIdentifier (UUID/Public key/String) – String
  * CurrentSharedSymmetricEncryptionKey
  * NextSharedSymmetricEncryptionKey (future support for key rotation)
  * Ed25519PublicKey (for hash signature verification)

* Examples of data within the address book

Alice's address book
| UserID   | CurrentSharedSymmetricEncryptionKey | Ed25519PublicKey    |
|----------|--------------------|--------------|
| bobId    | *BobAliceShared*     | BobPubKey    |
| carlosId | **CarlosAliceShared**  | CarlosPubKey |

Bob's address book
| UserID   | CurrentSharedSymmetricEncryptionKey | Ed25519PublicKey    |
|----------|--------------------|--------------|
| aliceId    | *BobAliceShared*     | AlicePubKey    |
| carlosId | ***BobCarlosShared***  | CarlosPubKey |
| carolId | BobCarolShared | CarolPubKey |

Carlos' address book
| UserID   | CurrentSharedSymmetricEncryptionKey | Ed25519PublicKey    |
|----------|--------------------|--------------|
| aliceId    | **CarlosAliceShared**     | AlicePubKey    |
| bobId | ***BobCarlosShared***  | BobPubKey |

**Alternatives**
Without this, no symmetric encryption can be implemented in hcs-sxc-core

**Comment by zoperado** [comment]
#423 addresses most except:
CurrentSharedSymmetricEncryptionKey
NextSharedSymmetricEncryptionKey (future support for key rotation)
,which could be on own Issue
