### ISSUE TITLE
hcs-core: receive HCS Message from mirror node

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-hcs-sxc-java#411]
**Problem**
Receiving messages encrypted with symmetric encryption isn't supported.

**Solution**
(see attached PDF for additional detail)

* Assemble all `ApplicationMessageChunks`

* If `applicationMessage.unencryptedBusinessProcessMessageHash` is not null/blank
  -> for each row in the address book
  -> attempt to verify `applicationMessage.businessProcessSignatureOnHash` with `ED25519PublicKey`
  -> if successful, decrypt message with sharedSymmetricKey, then SHA384 hash the decrypted message and check hash matches `applicationMessage.unencryptedBusinessProcessMessageHash`
  -> log error if match fails
  -> log info if signature match fails on all entries in the address book
  -> Store message data and chunks per `persistenceLevel` requirements
  -> if decryption and hash validation succeed, send unencrypted message to application

* If `applicationMessage.unencryptedBusinessProcessMessageHash` is null/blank
  -> if `applicationMessage.businessProcessSignatureOnHash` is not null/blank
  -> SHA384 hash the unencrypted message
  -> for each row in the address book
  -> verify signature on above hash against signature in message
  -> if no match found against any entry in the address book, log error and do not send message to application
  -> if match found, send unencrypted message to application

**Alternatives**
No symmetric encryption possible.

[message-handling.pdf](https://github.com/hashgraph/hedera-hcs-sxc-java/files/4225073/message-handling.pdf)

**Comment by zoperado** [comment]
The workflow has been implemented with the added logic: upon receipt of an encrypted message, a test is performed to detect whether the message is intended for the recipient and if so an attempt to decrypt is performed. In particular, the recipient tests the signature to determine if the originator is a known entity in his address-book, if not the message is skipped. If the message is from a known originator then the recipient still requires to test all shared keys to determine if he/she is the destined recipient of the message. 

Messages are either plain text messages or protobuffer messages; in the latter case, any proto message can be used and there are  two designated messages that are specific to key rotation; one to detect key rotation initiation and one to detect a response .

**Comment by zoperado** [comment]
Pair wise crypto final #426 closes this issue
