### ISSUE TITLE
Simple Message Demo - CreateTopic looks for .env in folder root instead of ./config/

### ISSUE THREAD

**Issue by zoperado** [hashgraph/hedera-hcs-sxc-java#417]
**Detailed Description**

**Actual Behavior**

**Expected Behavior**

**Environment:**
- Java: [e.g. OpenJDK 11.0.4]
- Node: [e.g. v12.9.1-x86]
- OS: [e.g. Ubuntu 18.04]
- Version: [e.g. 1.0.1]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by gregscullard** [comment]
Will be closed with pair-wise encryption PR.

**Comment by zoperado** [comment]
fixed with PR #426
