### ISSUE TITLE
hcs-sxc-core: not passing sequence, hash and timestamp back to app

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-hcs-sxc-java#443]
**Detailed Description**
Core only sends the original message back to the app, it would be ideal if the app could also receive the timestamp and sequence number, optionally the hash

**Comment by zoperado** [comment]
It does so indirectly. Core stores a message in database and all these
properties .  The app then can request to see that info ( simple message
demo demonstrates this )
